### ISSUE TITLE
analysis_options: linter ignores excluded files

### ISSUE THREAD

**Issue by soloproyectos** [dart-atom/dartlang#1070]
The following configuration works well. When I open the Atom editor, it doesn't show any warning. Except when I open any of the excluded files. Then, it shows the "info" messages.

```yaml
analyzer:
  strong-mode: true
  exclude:
    - test/**
linter:
  rules:
    - always_declare_return_types
    - always_specify_types
```

I think that Atom shouldn't print the "info" messages, even though any of those excluded files are being edited.
