### ISSUE TITLE
When editing the bottom of a file the error window hides the editing

### ISSUE THREAD

**Issue by vlidholt** [dart-atom/dartlang#127]
When adding code at the bottom of a long file the display of the errors will resize and hide the code currently being edited.

**Comment by devoncarew** [comment]
I'm not sure what the best solution here is. Some other tools solve this problems by always displaying a problems view, and at a fixed height (or user adjustable height). That way the number of errors doesn't cause the view to pop up a obscure what the user's typing.

There's the slight chance we could scroll the editor intelligently when resizing the linting view. Not sure how fragile that would be.

In the short term, here's some css you can put in your local style sheet:

```css
linter-panel {
  max-height: 70px;
  height: 70px;
}

linter-panel[hidden] {
  display: block !important;
}
```

That will always display the linter view. If you only put in the max-height section, it'll at least limit how much of your code the linter area can obscure.
